name = "SHTnsKit"
uuid = "1b9d0af0-2e90-4fb0-9eae-4a2e2cdf5320"
authors = ["Subhajit Kar <subhajitkar19@gmail.com>"]
version = "1.0.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SHTns_jll = "daf09cc5-9ab3-509e-9618-0b89086eb825"

[weakdeps]
CUDA = "082447d4-558c-5d27-93f4-14fc19e9eca2"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
SHTnsKitCUDAExt = "CUDA"
SHTnsKitForwardDiffExt = "ForwardDiff"
SHTnsKitMPIExt = "MPI"
SHTnsKitZygoteExt = ["Zygote", "ChainRulesCore"]

[compat]
CUDA = "5"
ChainRulesCore = "1"
FFTW = "1.7"
ForwardDiff = "0.10"
Libdl = "1"
LinearAlgebra = "1"
MPI = "0.20"
SHTns_jll = "3"
Zygote = "0.6"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
