name = "SHTnsKit"
uuid = "1b9d0af0-2e90-4fb0-9eae-4a2e2cdf5320"
authors = ["Subhajit Kar <subhajitkar19@gmail.com>"]
version = "1.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.10"
CUDA = "5"
MPI = "0.20"
ForwardDiff = "0.10"
Zygote = "0.6"
LinearAlgebra = "1"
Libdl = "1"
FFTW = "1.7"

[weakdeps]
CUDA = "082447d4-558c-5d27-93f4-14fc19e9eca2"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
SHTnsKitCUDAExt = "CUDA"
SHTnsKitMPIExt = "MPI"
SHTnsKitForwardDiffExt = "ForwardDiff"
SHTnsKitZygoteExt = "Zygote"
