[[FFTW]]
arch = "aarch64"
git-tree-sha1 = "3c8796930134b071e509bc43edb7ca86cbf5ac38"
os = "macos"

    [[FFTW.download]]
    sha256 = "b32f1ebb9567cf594e8117729ba40bd9ab0160bf6f14367636537837ec244eb1"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.aarch64-apple-darwin.tar.gz"
[[FFTW]]
arch = "aarch64"
git-tree-sha1 = "48fff0bd40a8838184d6f8b1533eb725cf2a0042"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "f4d105102eab5a87a1b71587838b6801f01211718d260bb78a01c12f2d1e22bc"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.aarch64-linux-gnu.tar.gz"
[[FFTW]]
arch = "aarch64"
git-tree-sha1 = "1bb5880f34496da071841ddf1cee65d5bbd98412"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "1c04858b6663733998e80069ca16dd1bbb1e0bc122dc327fe077b851a978a158"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.aarch64-linux-musl.tar.gz"
[[FFTW]]
arch = "aarch64"
git-tree-sha1 = "c349a507936a185891dabd01fb61ad01f9ed7a6c"
os = "freebsd"

    [[FFTW.download]]
    sha256 = "e0be5826f3c41a0e48c6eac3bb59010532ae44293b381b2a7cf9bdd9ae2c4b25"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.aarch64-unknown-freebsd.tar.gz"
[[FFTW]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a83bdf902399e02189bec719090392e96d0b6c57"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "28d6406de77f3f479c2fc1cd82104b8d2a457e2bdc781b520b7073b6f12381ea"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.armv6l-linux-gnueabihf.tar.gz"
[[FFTW]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6d4e7053060a85fd70beb74ab9f28014638ea48b"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "dba99116a7dc91f17d720aa93409b3dcd9ce6b57e35867f435ee5cfc816e5087"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.armv6l-linux-musleabihf.tar.gz"
[[FFTW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ee1a77df5e9fba4651e8dc8322c05abf43090c81"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "4eaa39867a49ed0da30b487e971e6f2365fde92400e801b217d6861ff615e976"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.armv7l-linux-gnueabihf.tar.gz"
[[FFTW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9e16a85fc79e1406c7e0a04f308626a00735d8e8"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "299f9c166e739aa9916daa59e3a719c063ac60cff64c7297335cb4ed7ec60409"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.armv7l-linux-musleabihf.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "175f5583205b45897a93f646d81607aec1708508"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "6cac5d714cc72420bc5e0dd386247bbbac365caf8c8d9f38ce70b941123d0b23"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.i686-linux-gnu.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "851901cf30cef76e2e086973c12c567a2f87307b"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "7d8e1cf5f63982409e9a132e13747b712b38e3d3bd6821a46a0189b181efdc24"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.i686-linux-musl.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "3ff919658d113fa486b0d293f7db028c31483d50"
os = "windows"

    [[FFTW.download]]
    sha256 = "cede3e0468a169da32fbbfda3885b15575d3362aeb718553e5be1cf7972261e4"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.i686-w64-mingw32.tar.gz"
[[FFTW]]
arch = "powerpc64le"
git-tree-sha1 = "57080889b64bf8ecb22b5da5d57bf01a39e3823a"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "b5645c3035568ae83b36a51375415460708091377f67b989e9c6ff966689fa24"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.powerpc64le-linux-gnu.tar.gz"
[[FFTW]]
arch = "riscv64"
git-tree-sha1 = "abbed30721c58eacda32678b78c646cf073a148a"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "66d4229a949033f0250ccea3db815619cc901956598c196b6fecfbba78df84f5"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.riscv64-linux-gnu.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "24e18b2608db544d7b04ca0e616e822f467faea0"
os = "macos"

    [[FFTW.download]]
    sha256 = "0b0d42d3ab3858b3e31a212809f8d0e498bfc83adf6d4e86e0ff4fb876e61273"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.x86_64-apple-darwin.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "8655261cdb15792fb0d954f81fb65ca24dc89fb5"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "8e66b17ee2a1f181d381e1b054350938de58ae6a561ebaf2c8d2f5eddd1a7189"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.x86_64-linux-gnu.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "3fe275f662ffd7020f5deb8eaa89167465bce1be"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "7582c2c43af18a8ae9ee3e782b9a6cb904749c613d75e93ebf8933ef1a6a4f59"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.x86_64-linux-musl.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "7bf0a1a3e83d98778e77c42e3b11331ab0a58351"
os = "freebsd"

    [[FFTW.download]]
    sha256 = "257d412eb70f6d87e24474d154543069291a050c3ce1ba4a0b3e166371b7e7ce"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.x86_64-unknown-freebsd.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "d8058cb6c6ee4c9d5cde3aed148cf80c4fb5c91e"
os = "windows"

    [[FFTW.download]]
    sha256 = "1784cbd3d14a39c3d59e9b09aa7f96391d9c24068635226864e1b0be3a1216e3"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.11+0/FFTW.v3.3.11.x86_64-w64-mingw32.tar.gz"
