[[IntelOpenMP]]
arch = "x86_64"
git-tree-sha1 = "0acf350efdf0dfc8dc7ab9d79ed22e90e0c2e807"
lazy = true
libc = "glibc"
os = "linux"

    [[IntelOpenMP.download]]
    sha256 = "0b5ad62b63789a0c63a07cc8dc985b0c2fa39f77fa3f94312007904b502e83d4"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2025.2.0+0/IntelOpenMP.v2025.2.0.x86_64-linux-gnu.tar.gz"
[[IntelOpenMP]]
arch = "x86_64"
git-tree-sha1 = "a1ec85a99cd05b478a5382f3e6f7a917d55f0b7e"
lazy = true
os = "windows"

    [[IntelOpenMP.download]]
    sha256 = "036a05947867e772c558a2a9dc489d2bf8ee48f6f3fc53a0a3976c1416ea650b"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2025.2.0+0/IntelOpenMP.v2025.2.0.x86_64-w64-mingw32.tar.gz"
