[[oneTBB]]
arch = "aarch64"
git-tree-sha1 = "e17e3b75f044705ab7ffa2be9a08f8a47266ad00"
os = "macos"

    [[oneTBB.download]]
    sha256 = "fd3a9cc4431fb5f752acc3bb77dabdf764b2defc3d42fa2eb9685fa99201e99b"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.aarch64-apple-darwin.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90794c859c56bcad449946ffeaf5117c5b62093b"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "01819b199a6661f3441078dbcd577e70ad2af0acba4c7e734f0a0be97f39208b"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72cdf2018de0845589f945226537a9309a2f447c"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "87616d7b1d30ce8bfbdeb165d873568c912a960ad1a6ede46d0e03c446d79029"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa4b7c3cd9695cdf0124488856860aed46c7dc2b"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "f7cd53e8d1e8aee80789a8b8d6d8d3162270c298fb9f5aeab25eebf982fdd67c"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8978fc27140ce58d6f14bc34a51d5db7cb483f0"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "b98c72b6f089bacea7c11ec63a2469ab7da890c7f63864140f5eb00f7e9162b5"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "aarch64"
git-tree-sha1 = "6c22fe62825b972ee259219acd650edbdd3df40e"
os = "freebsd"

    [[oneTBB.download]]
    sha256 = "b0f37aa14481ada16ae74981115d52af5c0d5a3065cc56ba9e152d1b2a0b5287"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.aarch64-unknown-freebsd.tar.gz"
[[oneTBB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d052128c1563265996b6eaa78fe0b79234ab880"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "1b428f9c589ba00d97e4bdba17794a44efd843aa0736bbf6e0822f33b71b954f"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[oneTBB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0b4d9e27ef8e8ed27296a676344df1d9dbf93b5"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "20093ce3c89c429cfa8a60d58dd51bcb7f63e62837b7a605743348ad7ed374c8"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[oneTBB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8985d69612a29ba51f3c1ac6f18f5dee44b9719a"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "c2e078bff93f3b12f543c24cb271b3140a4e3416fea882e63401f42c071c0c40"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[oneTBB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "390f6e2d8223ad5130c1c82de6bf54aafcc0f105"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "33b424e4cd5c4912b86a9d2e4a19f32442736922b1a92eafc8f0199ac6e04303"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[oneTBB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e94cbd95210f6e4ba40dce9fb359ba416d78490"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "500d5c54d7a16b670833db133cebe3fec5bee52a29a952cf65241405cf1c43ec"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[oneTBB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35cd5510faff86f67b7c30f215f8c091890c8869"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "8776c3a472297274f7bb83faa9ddeeeaff9ef6fe955498c21baf50510f5d88b1"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[oneTBB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e83fb5a64aa8bc6c529916d68e389d9aa67931cb"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "67d393255018f213223d1ab9765dc9cd2f00f8150c38a0697330e6ba98570174"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[oneTBB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b484f19362105d01899be48a2272f945614007a4"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "3a771b338e7a8c6b4bc031d7dbd99d76b041394e1f1e852422d8cf332babe723"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "683c01d2de719e177098f0ce7fcccf2def10b691"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "e123c083c875807576ebf32792aa837e819d6bef2be19ed99ce81917c0aa8000"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.i686-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b6b738974379bdbaaab5da70690d1ce0777787a"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "239fdb62b622884f3839890f5091356fff3292fdc033e7afa258e840ba839339"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.i686-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "234115d75866d1f129f4d17477ebd8d954e5318e"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "807182b31b630589ad8a214851dbfe4da745c352ddd58eefb4a0c7cb5b80e200"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.i686-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3dceca5ff961f977588b7c1c37a76ca7e217109"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "0293779c3174ab8aa52cb9272a807a474473f4b227f311ca9205174ea1212c97"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.i686-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e13da2d90d67fe9f403a9d703ad55980312d794"
os = "windows"

    [[oneTBB.download]]
    sha256 = "be68f7c09bc2dc82596d449fddaaaf9152f8d731d1ea7eb375849fb3369d34d2"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "973eabecae313446379b9c06870d4603861d05dc"
os = "windows"

    [[oneTBB.download]]
    sha256 = "3641fa5aa68f38a3c16860ed38ca2bb03c2f384529d827983b8eee16de416948"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[oneTBB]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d34582bac38f172894238cfc206227ef5b3b7b64"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "91d077715cae0bb003f64c765109ab58a6ce9765078f17b883ab61c0d9017479"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5ee8f0413bb04fc42d76efd2e2346f255cd9187"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "6ca6eb8427864489abbc7f47b33b0d93f7af6c838e72e033f33795755de27e48"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f915deae58fa18346f25baee603d6574a804528b"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "65617fc71eb1340c1b666738399e7b2b78814388225328b1a081f24737582f6f"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.riscv64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f915deae58fa18346f25baee603d6574a804528b"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "65617fc71eb1340c1b666738399e7b2b78814388225328b1a081f24737582f6f"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
git-tree-sha1 = "e0af13d4fb7615a4ea97e9922c8ac5a902924608"
os = "macos"

    [[oneTBB.download]]
    sha256 = "8b1561a6137f4fcd77be5b11c75b089ba9abeaf4f873512d7c5ec91e24057864"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.x86_64-apple-darwin.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "569baa4ca429b86b2d51506240fc569bbb78a487"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "cb59c6727bcd2640b0bc23abce3094b7bacc6c59c59fee89ef7b9856d2c55a07"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc6a577e335709d64448aa4ed7fa1bed0b2dc000"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "eece12bfe8ef15a8f190fadfde4854eef1a61e05cadf26258bca58362e63b9d3"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8fd71887a1e74a2e9db48c13688c4141a91c5948"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "fd655d85060313a0e7830f88484d97d720c395efec0471ffa1363f440306d28d"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c4bb1cb6805037ff17b3f521ce571d43fb09d2e"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "c5c4bc42dfcecc4e9cb29ee3735336b66b0f1de3175cbee186532a32cff3a879"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
git-tree-sha1 = "fc0d4638511e57cb899f44f2ae4eb7aa85013e54"
os = "freebsd"

    [[oneTBB.download]]
    sha256 = "7912f25fc3e4835a5c6334f360dc874be0316e5f0a20952b8a143796eaaa6906"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.x86_64-unknown-freebsd.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27481b853c0c863c16c72acdaf2dcd6c15374374"
os = "windows"

    [[oneTBB.download]]
    sha256 = "5ff9cdf1b1f918c2814dc2efcc6f33b7ebb1c425d2118374e268e7ef08fc9b6b"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41ef323658240d98dd24a78f07fe284c212fd3fb"
os = "windows"

    [[oneTBB.download]]
    sha256 = "e73c4cb3e6d70ac5edf5fb9f66de1541ef79ad32663867bf58dee530ce7329d0"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+0/oneTBB.v2022.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
