name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1.11'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      
      - uses: julia-actions/cache@v1
      
      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gfortran libfftw3-dev
          
      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install fftw gcc
          
      - name: Build package
        run: |
          echo "Building package..."
          julia --project=. -e '
            using Pkg
            println("Julia version: ", VERSION)
            println("Installing dependencies...")
            Pkg.instantiate()
            println("Precompiling...")
            Pkg.precompile()
            println("Build completed!")'
      
      - name: Run tests
        run: |
          echo "Running tests..."
          julia --project=. -e '
            using Pkg
            Pkg.test()
            println("Tests completed!")'
        env:
          # Help with SHTns accuracy test issues
          JULIA_PKG_TEST: "true"
          # Limit OpenMP threads to avoid oversubscription in CI
          OMP_NUM_THREADS: 2
          OPENBLAS_NUM_THREADS: 1

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'
          
      - uses: julia-actions/cache@v1
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gfortran libfftw3-dev
      
      - name: Build documentation
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            include("docs/make.jl")'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}