name: Documentation

on:
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

# Cancel in-progress documentation builds for the same PR/branch  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: Documentation Preview
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
          
      - name: Cache Julia packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.julia/packages
            ~/.julia/compiled
          key: ${{ runner.os }}-julia-docs-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-docs-
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gfortran libfftw3-dev
      
      - name: Set up documentation environment
        run: |
          cd docs
          julia --project=. -e '
            using Pkg
            Pkg.develop(PackageSpec(path=".."))
            Pkg.instantiate()
            Pkg.precompile()
          '
      
      - name: Build documentation (preview)
        run: |
          cd docs
          julia --project=. make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          
      - name: Upload documentation preview
        uses: actions/upload-artifact@v4
        with:
          name: documentation-preview
          path: docs/build
