name: E2E with Local JLL

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  e2e:
    name: SHTnsKit tests using local JLL on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Cache Julia packages
        uses: julia-actions/cache@v1

      - name: Instantiate and dev local JLL (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          julia --project=. -e '
            using Pkg
            Pkg.develop(path="SHTnsKit_jll")
            Pkg.instantiate()
            println("Developed SHTnsKit_jll: ", joinpath(pwd(), "SHTnsKit_jll"))
          '

      - name: Run SHTnsKit tests (prefers local JLL on Linux)
        env:
          OMP_NUM_THREADS: "2"
          OPENBLAS_NUM_THREADS: "1"
          # Keep default SHTns tests policy unless explicitly toggled
          # SHTNSKIT_TEST_SHTNS: "false"
        run: |
          julia --project=. -e '
            using Pkg
            Pkg.test()
          '
