name: TagBot

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      lookback:
        description: 'How many days back to check for new JuliaRegistrator merges'
        required: false
        default: '7'  # Increased default lookback

permissions:
  contents: write
  issues: read
  pull-requests: read

jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}  # Uncomment if you have SSH keys set up
